// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ReilEgor/RepoNotifier/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryRepository is an autogenerated mock type for the RepositoryRepository type
type RepositoryRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *RepositoryRepository) GetAll(ctx context.Context) ([]model.Repository, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Repository, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Repository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreate provides a mock function with given fields: ctx, name, tagName
func (_m *RepositoryRepository) GetOrCreate(ctx context.Context, name string, tagName string) (*model.Repository, error) {
	ret := _m.Called(ctx, name, tagName)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *model.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Repository, error)); ok {
		return rf(ctx, name, tagName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Repository); ok {
		r0 = rf(ctx, name, tagName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, tagName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastSeenTag provides a mock function with given fields: ctx, name, tag
func (_m *RepositoryRepository) UpdateLastSeenTag(ctx context.Context, name string, tag string) error {
	ret := _m.Called(ctx, name, tag)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSeenTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryRepository creates a new instance of RepositoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryRepository {
	mock := &RepositoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
