// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ReilEgor/RepoNotifier/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionUseCase is an autogenerated mock type for the SubscriptionUseCase type
type SubscriptionUseCase struct {
	mock.Mock
}

// ListByEmail provides a mock function with given fields: ctx, email
func (_m *SubscriptionUseCase) ListByEmail(ctx context.Context, email string) ([]model.Subscription, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ListByEmail")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Subscription, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Subscription); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessNotifications provides a mock function with given fields: ctx
func (_m *SubscriptionUseCase) ProcessNotifications(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, email, repoName
func (_m *SubscriptionUseCase) Subscribe(ctx context.Context, email string, repoName string) (int64, error) {
	ret := _m.Called(ctx, email, repoName)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, email, repoName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, email, repoName)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, repoName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unsubscribe provides a mock function with given fields: ctx, email, repoName
func (_m *SubscriptionUseCase) Unsubscribe(ctx context.Context, email string, repoName string) error {
	ret := _m.Called(ctx, email, repoName)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, repoName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscriptionUseCase creates a new instance of SubscriptionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionUseCase {
	mock := &SubscriptionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
