// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ReilEgor/RepoNotifier/internal/config"
	"github.com/ReilEgor/RepoNotifier/internal/domain/repository"
	"github.com/ReilEgor/RepoNotifier/internal/domain/service"
	usecase2 "github.com/ReilEgor/RepoNotifier/internal/domain/usecase"
	"github.com/ReilEgor/RepoNotifier/internal/infrastructure/cache/redis"
	"github.com/ReilEgor/RepoNotifier/internal/infrastructure/clients/email"
	"github.com/ReilEgor/RepoNotifier/internal/infrastructure/clients/github"
	"github.com/ReilEgor/RepoNotifier/internal/infrastructure/storage/postgres"
	postgres2 "github.com/ReilEgor/RepoNotifier/internal/repository/postgres"
	"github.com/ReilEgor/RepoNotifier/internal/transport/http"
	"github.com/ReilEgor/RepoNotifier/internal/transport/http/handlers"
	"github.com/ReilEgor/RepoNotifier/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, redisHost config.RedisHostType, redisPort config.RedisPortType, redisPassword config.RedisPasswordType, redisDB int, dsn config.DSNType, emailHost config.EmailHostType, emailPort config.EmailPortType, emailPassword config.EmailPasswordType, emailFrom config.EmailFromType, emailUser config.EmailUserType) (*App, func(), error) {
	pool, cleanup, err := postgres.New(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	subscriptionRepository := postgres2.NewSubscriptionRepository(pool)
	client, err := redis.NewRedisClient(redisHost, redisPort, redisPassword, redisDB)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cache := redis.NewCache(client)
	gitHubClient := github.NewGitHubClient(cache)
	userRepository := postgres2.NewUserRepository(pool)
	repositoryRepository := postgres2.NewRepositoryRepository(pool)
	smtpClient := email.NewSmtpClient(emailHost, emailPort, emailFrom, emailPassword, emailUser)
	subscriptionUseCase := usecase.NewSubscriptionUseCase(subscriptionRepository, gitHubClient, userRepository, repositoryRepository, smtpClient)
	userUseCase := usecase.NewUserUseCase(userRepository)
	ginServer := http.NewGinServer(subscriptionUseCase, userUseCase, client)
	app := &App{
		Server:              ginServer,
		SubscriptionUseCase: subscriptionUseCase,
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

var UseCaseSet = wire.NewSet(usecase.NewSubscriptionUseCase, usecase.NewUserUseCase, wire.Bind(new(usecase2.UserUseCase), new(*usecase.UserUseCase)), wire.Bind(new(usecase2.SubscriptionUseCase), new(*usecase.SubscriptionUseCase)))

var RepositorySet = wire.NewSet(postgres.New, postgres2.NewRepositoryRepository, postgres2.NewSubscriptionRepository, postgres2.NewUserRepository, wire.Bind(new(repository.RepositoryRepository), new(*postgres2.RepositoryRepository)), wire.Bind(new(repository.SubscriptionRepository), new(*postgres2.SubscriptionRepository)), wire.Bind(new(repository.UserRepository), new(*postgres2.UserRepository)))

var RestSet = wire.NewSet(http.NewGinServer, handlers.NewHandler)

var CacheSet = wire.NewSet(redis.NewRedisClient, redis.NewCache, wire.Bind(new(service.Cache), new(*redis.Cache)))

var ServicesSet = wire.NewSet(github.NewGitHubClient, email.NewSmtpClient, wire.Bind(new(service.EmailSender), new(*email.SmtpClient)), wire.Bind(new(service.GitHubClient), new(*github.GitHubClient)))

type App struct {
	Server              *http.GinServer
	SubscriptionUseCase usecase2.SubscriptionUseCase
}
